package com.mgd.bookstore.config;

import com.mgd.bookstore.model.Book;
import com.mgd.bookstore.model.Category;
import com.mgd.bookstore.repository.BookRepository;
import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import java.math.BigDecimal;
import java.util.List;

@Configuration
public class DataLoader {

    @Bean
    CommandLineRunner seedBooks(BookRepository bookRepository) {
        return args -> {
            if (bookRepository.count() > 0) return; // skip if already seeded
            System.out.println(">>> DataLoader triggered");

            List<Book> books = List.of(
                    // FICTION (15)
                    book("The Midnight Library", "Matt Haig",
                            "499.00", "A library between life and death holds every book of a life you could have lived.",
                            List.of(Category.FICTION)),
                    book("Lessons in Chemistry", "Bonnie Garmus",
                            "549.00", "A female chemist in the 1960s becomes the star of a cooking show, upending societal norms.",
                            List.of(Category.FICTION)),
                    book("The Alchemist", "Paulo Coelho",
                            "379.00", "A shepherd boy travels from Spain to Egypt in search of treasure and self-discovery.",
                            List.of(Category.FICTION)),
                    book("Normal People", "Sally Rooney",
                            "429.00", "Two students from the west of Ireland navigate their complex relationship over years.",
                            List.of(Category.FICTION)),
                    book("Where the Crawdads Sing", "Delia Owens",
                            "529.00", "A girl raised alone in the marshes of North Carolina becomes a murder suspect.",
                            List.of(Category.FICTION)),
                    book("The Kite Runner", "Khaled Hosseini",
                            "459.00", "A story of friendship, betrayal, and redemption set against the backdrop of Afghanistan.",
                            List.of(Category.FICTION)),
                    book("A Little Life", "Hanya Yanagihara",
                            "699.00", "Four college friends navigate trauma, ambition, and love in New York City.",
                            List.of(Category.FICTION)),
                    book("Anxious People", "Fredrik Backman",
                            "489.00", "A bank robbery gone wrong leads to an apartment viewing hostage situation.",
                            List.of(Category.FICTION)),
                    book("The Dutch House", "Ann Patchett",
                            "469.00", "A brother and sister are haunted by the loss of their family home across decades.",
                            List.of(Category.FICTION)),
                    book("Pachinko", "Min Jin Lee",
                            "579.00", "An epic saga of a Korean family's struggles across four generations in Japan.",
                            List.of(Category.FICTION)),
                    book("The God of Small Things", "Arundhati Roy",
                            "449.00", "Twin siblings in Kerala, India, face tragedy shaped by the laws of love and society.",
                            List.of(Category.FICTION)),
                    book("Klara and the Sun", "Kazuo Ishiguro",
                            "519.00", "An Artificial Friend observes human behavior while waiting to be chosen in a shop.",
                            List.of(Category.FICTION)),
                    book("One Hundred Years of Solitude", "Gabriel García Márquez",
                            "499.00", "Seven generations of the Buendía family in the fictional town of Macondo.",
                            List.of(Category.FICTION)),
                    book("The House on Mango Street", "Sandra Cisneros",
                            "349.00", "A young Latina girl grows up in the Hispanic quarter of Chicago.",
                            List.of(Category.FICTION)),
                    book("Circe", "Madeline Miller",
                            "539.00", "The mythological witch Circe discovers her powers and forges her own path.",
                            List.of(Category.FICTION, Category.FANTASY)),

                    // NON_FICTION (15)
                    book("Sapiens", "Yuval Noah Harari",
                            "599.00", "A brief history of humankind from the Stone Age to the 21st century.",
                            List.of(Category.NON_FICTION, Category.HISTORY)),
                    book("Atomic Habits", "James Clear",
                            "549.00", "A proven framework for building good habits and breaking bad ones.",
                            List.of(Category.NON_FICTION)),
                    book("Educated", "Tara Westover",
                            "529.00", "A memoir of a woman who grows up in a survivalist family and educates herself.",
                            List.of(Category.NON_FICTION)),
                    book("Thinking, Fast and Slow", "Daniel Kahneman",
                            "649.00", "An exploration of the two systems that drive the way we think.",
                            List.of(Category.NON_FICTION)),
                    book("The Body Keeps the Score", "Bessel van der Kolk",
                            "579.00", "How trauma reshapes body and brain, and innovative treatments for recovery.",
                            List.of(Category.NON_FICTION)),
                    book("Bad Blood", "John Carreyrou",
                            "519.00", "The rise and fall of Theranos and Elizabeth Holmes' billion-dollar fraud.",
                            List.of(Category.NON_FICTION)),
                    book("Becoming", "Michelle Obama",
                            "599.00", "An intimate memoir by the former First Lady of the United States.",
                            List.of(Category.NON_FICTION)),
                    book("The Subtle Art of Not Giving a F*ck", "Mark Manson",
                            "449.00", "A counterintuitive approach to living a good life by embracing limitations.",
                            List.of(Category.NON_FICTION)),
                    book("Outliers", "Malcolm Gladwell",
                            "479.00", "Why some people succeed and what we can learn from them.",
                            List.of(Category.NON_FICTION)),
                    book("When Breath Becomes Air", "Paul Kalanithi",
                            "469.00", "A neurosurgeon faces his own mortality after a terminal cancer diagnosis.",
                            List.of(Category.NON_FICTION)),
                    book("Man's Search for Meaning", "Viktor E. Frankl",
                            "379.00", "A psychiatrist's memoir of surviving Nazi concentration camps.",
                            List.of(Category.NON_FICTION, Category.HISTORY)),
                    book("The Power of Now", "Eckhart Tolle",
                            "429.00", "A guide to spiritual enlightenment through present-moment awareness.",
                            List.of(Category.NON_FICTION)),
                    book("Born a Crime", "Trevor Noah",
                            "489.00", "Stories of growing up mixed-race in apartheid South Africa.",
                            List.of(Category.NON_FICTION, Category.HISTORY)),
                    book("Quiet", "Susan Cain",
                            "499.00", "The power of introverts in a world that can't stop talking.",
                            List.of(Category.NON_FICTION)),
                    book("Factfulness", "Hans Rosling",
                            "519.00", "Ten reasons we're wrong about the world and why things are better than you think.",
                            List.of(Category.NON_FICTION)),

                    // SCIENCE (15)
                    book("A Brief History of Time", "Stephen Hawking",
                            "499.00", "From the Big Bang to black holes — a landmark exploration of the universe.",
                            List.of(Category.SCIENCE)),
                    book("The Selfish Gene", "Richard Dawkins",
                            "529.00", "How genes shape behavior and evolution from a gene-centric perspective.",
                            List.of(Category.SCIENCE)),
                    book("Cosmos", "Carl Sagan",
                            "549.00", "A personal voyage through space, time, and the human understanding of the universe.",
                            List.of(Category.SCIENCE)),
                    book("The Gene", "Siddhartha Mukherjee",
                            "599.00", "An intimate history of the gene and its role in medicine and identity.",
                            List.of(Category.SCIENCE)),
                    book("Astrophysics for People in a Hurry", "Neil deGrasse Tyson",
                            "399.00", "The most important ideas in astrophysics compressed into an accessible read.",
                            List.of(Category.SCIENCE)),
                    book("The Hidden Life of Trees", "Peter Wohlleben",
                            "469.00", "What trees feel and how they communicate — discoveries from a secret world.",
                            List.of(Category.SCIENCE)),
                    book("The Immortal Life of Henrietta Lacks", "Rebecca Skloot",
                            "519.00", "The story of the woman whose cells changed medicine without her knowledge.",
                            List.of(Category.SCIENCE, Category.NON_FICTION)),
                    book("Surely You're Joking, Mr. Feynman!", "Richard P. Feynman",
                            "489.00", "Adventures of a curious character — anecdotes from a Nobel Prize-winning physicist.",
                            List.of(Category.SCIENCE, Category.NON_FICTION)),
                    book("The Elegant Universe", "Brian Greene",
                            "549.00", "Superstrings, hidden dimensions, and the quest for the ultimate theory.",
                            List.of(Category.SCIENCE)),
                    book("Six Easy Pieces", "Richard P. Feynman",
                            "429.00", "Essentials of physics explained from Feynman's legendary lectures.",
                            List.of(Category.SCIENCE)),
                    book("The Structure of Scientific Revolutions", "Thomas S. Kuhn",
                            "479.00", "How scientific progress happens through paradigm shifts, not gradual accumulation.",
                            List.of(Category.SCIENCE, Category.NON_FICTION)),
                    book("Behave", "Robert Sapolsky",
                            "599.00", "The biology of humans at our best and worst.",
                            List.of(Category.SCIENCE)),
                    book("The Sixth Extinction", "Elizabeth Kolbert",
                            "519.00", "An unnatural history of mass extinction driven by human activity.",
                            List.of(Category.SCIENCE, Category.NON_FICTION)),
                    book("How the Mind Works", "Steven Pinker",
                            "579.00", "An exploration of the mind's faculties — vision, thinking, emotions, and social relations.",
                            List.of(Category.SCIENCE)),
                    book("The Order of Time", "Carlo Rovelli",
                            "449.00", "A physicist unravels the mysteries of time in poetic, accessible prose.",
                            List.of(Category.SCIENCE)),

                    // TECHNOLOGY (15)
                    book("Clean Code", "Robert C. Martin",
                            "699.00", "A handbook of agile software craftsmanship for writing readable, maintainable code.",
                            List.of(Category.TECHNOLOGY)),
                    book("The Pragmatic Programmer", "David Thomas & Andrew Hunt",
                            "729.00", "Timeless lessons on software development from code to career.",
                            List.of(Category.TECHNOLOGY)),
                    book("Zero to One", "Peter Thiel",
                            "529.00", "Notes on startups and how to build companies that create new things.",
                            List.of(Category.TECHNOLOGY, Category.NON_FICTION)),
                    book("The Innovators", "Walter Isaacson",
                            "649.00", "How a group of hackers, geniuses, and geeks created the digital revolution.",
                            List.of(Category.TECHNOLOGY, Category.HISTORY)),
                    book("Life 3.0", "Max Tegmark",
                            "579.00", "Being human in the age of artificial intelligence.",
                            List.of(Category.TECHNOLOGY, Category.SCIENCE)),
                    book("The Phoenix Project", "Gene Kim",
                            "589.00", "A novel about IT, DevOps, and helping your business win.",
                            List.of(Category.TECHNOLOGY)),
                    book("Designing Data-Intensive Applications", "Martin Kleppmann",
                            "899.00", "The big ideas behind reliable, scalable, and maintainable systems.",
                            List.of(Category.TECHNOLOGY)),
                    book("Algorithms to Live By", "Brian Christian & Tom Griffiths",
                            "569.00", "The computer science of human decisions.",
                            List.of(Category.TECHNOLOGY, Category.NON_FICTION)),
                    book("The Second Machine Age", "Erik Brynjolfsson",
                            "549.00", "Work, progress, and prosperity in a time of brilliant technologies.",
                            List.of(Category.TECHNOLOGY, Category.NON_FICTION)),
                    book("Hooked", "Nir Eyal",
                            "479.00", "How to build habit-forming products using the Hook Model.",
                            List.of(Category.TECHNOLOGY)),
                    book("The Lean Startup", "Eric Ries",
                            "499.00", "How today's entrepreneurs use continuous innovation to create successful businesses.",
                            List.of(Category.TECHNOLOGY, Category.NON_FICTION)),
                    book("Code", "Charles Petzold",
                            "649.00", "The hidden language of computer hardware and software.",
                            List.of(Category.TECHNOLOGY)),
                    book("The Master Algorithm", "Pedro Domingos",
                            "559.00", "How the quest for the ultimate learning machine will remake our world.",
                            List.of(Category.TECHNOLOGY, Category.SCIENCE)),
                    book("Superintelligence", "Nick Bostrom",
                            "589.00", "Paths, dangers, and strategies for a future with machine superintelligence.",
                            List.of(Category.TECHNOLOGY, Category.SCIENCE)),
                    book("A Thousand Brains", "Jeff Hawkins",
                            "539.00", "A new theory of intelligence and the future of AI.",
                            List.of(Category.TECHNOLOGY, Category.SCIENCE)),

                    // HISTORY (10)
                    book("Guns, Germs, and Steel", "Jared Diamond",
                            "579.00", "The fates of human societies — why some civilizations conquered others.",
                            List.of(Category.HISTORY, Category.NON_FICTION)),
                    book("The Diary of a Young Girl", "Anne Frank",
                            "349.00", "The wartime diary of a Jewish girl hiding from the Nazis in Amsterdam.",
                            List.of(Category.HISTORY, Category.NON_FICTION)),
                    book("Homo Deus", "Yuval Noah Harari",
                            "599.00", "A brief history of tomorrow — what will happen to humanity and the planet.",
                            List.of(Category.HISTORY, Category.NON_FICTION)),
                    book("The Rise and Fall of the Third Reich", "William L. Shirer",
                            "849.00", "A comprehensive history of Nazi Germany from its rise to defeat.",
                            List.of(Category.HISTORY)),
                    book("1776", "David McCullough",
                            "529.00", "The story of Washington's army in the crucial year of American independence.",
                            List.of(Category.HISTORY)),
                    book("The Silk Roads", "Peter Frankopan",
                            "619.00", "A new history of the world told through the trade routes connecting East and West.",
                            List.of(Category.HISTORY, Category.NON_FICTION)),
                    book("SPQR", "Mary Beard",
                            "559.00", "A history of ancient Rome and how it became the world's first global superpower.",
                            List.of(Category.HISTORY)),
                    book("The Crusades", "Thomas Asbridge",
                            "589.00", "The authoritative history of the medieval holy wars for Jerusalem.",
                            List.of(Category.HISTORY)),
                    book("Alexander Hamilton", "Ron Chernow",
                            "749.00", "The definitive biography of one of America's Founding Fathers.",
                            List.of(Category.HISTORY, Category.NON_FICTION)),
                    book("Empire of the Sun", "J.G. Ballard",
                            "469.00", "A boy's survival in a Japanese internment camp during World War II.",
                            List.of(Category.HISTORY, Category.FICTION)),

                    // ROMANCE (15)
                    book("Pride and Prejudice", "Jane Austen",
                            "329.00", "Elizabeth Bennet navigates issues of manners, upbringing, and marriage in 19th-century England.",
                            List.of(Category.ROMANCE, Category.FICTION)),
                    book("The Notebook", "Nicholas Sparks",
                            "399.00", "A timeless story of a love that transcends time and memory.",
                            List.of(Category.ROMANCE, Category.FICTION)),
                    book("Outlander", "Diana Gabaldon",
                            "649.00", "A WWII nurse is swept back in time to 18th-century Scotland.",
                            List.of(Category.ROMANCE, Category.FICTION, Category.HISTORY)),
                    book("Me Before You", "Jojo Moyes",
                            "449.00", "A small-town girl becomes a carer for a wealthy, paralyzed man who changed her world.",
                            List.of(Category.ROMANCE, Category.FICTION)),
                    book("The Hating Game", "Sally Thorne",
                            "429.00", "Two executive assistants wage a battle of wills that turns into something more.",
                            List.of(Category.ROMANCE, Category.FICTION)),
                    book("It Ends with Us", "Colleen Hoover",
                            "469.00", "A woman must make the hardest decision of her life in a complicated romance.",
                            List.of(Category.ROMANCE, Category.FICTION)),
                    book("Beach Read", "Emily Henry",
                            "419.00", "Two rival authors swap genres for the summer — and find unexpected connection.",
                            List.of(Category.ROMANCE, Category.FICTION)),
                    book("The Kiss Quotient", "Helen Hoang",
                            "439.00", "An econometrician with Asperger's hires a male escort to help her understand relationships.",
                            List.of(Category.ROMANCE, Category.FICTION)),
                    book("People We Meet on Vacation", "Emily Henry",
                            "459.00", "Best friends who ruined everything try to recapture their magic on one last trip.",
                            List.of(Category.ROMANCE, Category.FICTION)),
                    book("The Spanish Love Deception", "Elena Armas",
                            "449.00", "A woman convinces a colleague to pose as her boyfriend at her sister's wedding.",
                            List.of(Category.ROMANCE, Category.FICTION)),
                    book("Book Lovers", "Emily Henry",
                            "459.00", "A cutthroat literary agent keeps bumping into the same editor in a small town.",
                            List.of(Category.ROMANCE, Category.FICTION)),
                    book("The Seven Husbands of Evelyn Hugo", "Taylor Jenkins Reid",
                            "499.00", "A reclusive Hollywood star finally tells the truth about her glamorous life.",
                            List.of(Category.ROMANCE, Category.FICTION)),
                    book("One Day in December", "Josie Silver",
                            "429.00", "A chance meeting at a bus stop sets off a decade-long love story.",
                            List.of(Category.ROMANCE, Category.FICTION)),
                    book("The Time Traveler's Wife", "Audrey Niffenegger",
                            "489.00", "A man with a genetic disorder involuntarily time travels, straining his marriage.",
                            List.of(Category.ROMANCE, Category.FICTION, Category.SCIENCE)),
                    book("Verity", "Colleen Hoover",
                            "479.00", "A struggling author uncovers a disturbing manuscript that changes everything.",
                            List.of(Category.ROMANCE, Category.FICTION)),

                    // FANTASY (15)
                    book("The Name of the Wind", "Patrick Rothfuss",
                            "599.00", "A legendary figure recounts his extraordinary life as a young orphan who becomes a legendary wizard.",
                            List.of(Category.FANTASY, Category.FICTION)),
                    book("The Way of Kings", "Brandon Sanderson",
                            "749.00", "An epic fantasy set in a world of storms, where ancient evils stir once more.",
                            List.of(Category.FANTASY, Category.FICTION)),
                    book("The Hobbit", "J.R.R. Tolkien",
                            "449.00", "Bilbo Baggins is swept into an epic quest to reclaim a dwarven homeland.",
                            List.of(Category.FANTASY, Category.FICTION)),
                    book("The Fellowship of the Ring", "J.R.R. Tolkien",
                            "549.00", "A young hobbit embarks on a perilous journey to destroy the One Ring.",
                            List.of(Category.FANTASY, Category.FICTION)),
                    book("A Game of Thrones", "George R.R. Martin",
                            "599.00", "Noble families fight for control of the Iron Throne in the Seven Kingdoms.",
                            List.of(Category.FANTASY, Category.FICTION)),
                    book("The Lies of Locke Lamora", "Scott Lynch",
                            "569.00", "A gang of con artists pulls off increasingly dangerous heists in a fantasy city.",
                            List.of(Category.FANTASY, Category.FICTION)),
                    book("Mistborn: The Final Empire", "Brandon Sanderson",
                            "579.00", "A crew of criminals plan to overthrow the seemingly immortal ruler of their world.",
                            List.of(Category.FANTASY, Category.FICTION)),
                    book("The Priory of the Orange Tree", "Samantha Shannon",
                            "699.00", "A world-building epic of queens, dragonriders, and ancient prophecy.",
                            List.of(Category.FANTASY, Category.FICTION)),
                    book("Piranesi", "Susanna Clarke",
                            "469.00", "A man lives alone in a mysterious house of infinite halls filled with statues and tides.",
                            List.of(Category.FANTASY, Category.FICTION)),
                    book("The Night Circus", "Erin Morgenstern",
                            "519.00", "Two magicians compete in an enchanting circus that only appears at night.",
                            List.of(Category.FANTASY, Category.FICTION, Category.ROMANCE)),
                    book("The Blade Itself", "Joe Abercrombie",
                            "549.00", "A barbarian, a crippled torturer, and a young soldier are drawn into a grand quest.",
                            List.of(Category.FANTASY, Category.FICTION)),
                    book("Assassin's Apprentice", "Robin Hobb",
                            "519.00", "The illegitimate son of a prince is trained as a royal assassin in a kingdom under siege.",
                            List.of(Category.FANTASY, Category.FICTION)),
                    book("The Poppy War", "R.F. Kuang",
                            "559.00", "A war orphan discovers she has a deadly power that could save or destroy her nation.",
                            List.of(Category.FANTASY, Category.FICTION, Category.HISTORY)),
                    book("Children of Blood and Bone", "Tomi Adeyemi",
                            "529.00", "A girl sets out to restore magic to her people in a West African-inspired world.",
                            List.of(Category.FANTASY, Category.FICTION)),
                    book("The Bear and the Nightingale", "Katherine Arden",
                            "509.00", "A girl with a gift for magic defies the creeping darkness in medieval Russia.",
                            List.of(Category.FANTASY, Category.FICTION, Category.HISTORY))
            );

            bookRepository.saveAll(books);
            System.out.println("✅ Seeded " + books.size() + " books into the database.");
        };
    }

    private Book book(String title, String author, String price, String description, List<Category> categories) {
        Book b = new Book();
        b.setTitle(title);
        b.setAuthor(author);
        b.setPrice(new BigDecimal(price));
        b.setDescription(description);
        b.setCategories(categories);
        b.setActive(true);
        return b;
    }
}